// esbuild.base.mjs
// Shared esbuild configuration factory used by every plugin's esbuild.config.mjs.
// Keeping this in one place means all plugins compile with the same rules
// (single bundle, obsidian/electron externals, banner, watch mode) while still
// producing an independent main.js per plugin.

import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
If you want to view the source, visit the plugin's repository
*/`;

/**
 * @param {object} options
 * @param {string} options.entryPoint - path to the plugin's src/main.ts
 * @param {string} options.outfile - path to the plugin's output main.js
 */
export async function buildPlugin({ entryPoint, outfile }) {
  const isProd = process.argv.includes("production");
  const isWatch = process.argv.includes("watch");

  const context = await esbuild.context({
    banner: { js: banner },
    entryPoints: [entryPoint],
    bundle: true,
    external: [
      "obsidian",
      "electron",
      "@codemirror/autocomplete",
      "@codemirror/collab",
      "@codemirror/commands",
      "@codemirror/language",
      "@codemirror/lint",
      "@codemirror/search",
      "@codemirror/state",
      "@codemirror/view",
      "@lezer/common",
      "@lezer/highlight",
      "@lezer/lr",
      ...builtins,
    ],
    format: "cjs",
    target: "es2020",
    logLevel: "info",
    sourcemap: isProd ? false : "inline",
    treeShaking: true,
    outfile,
    minify: isProd,
  });

  if (isWatch) {
    await context.watch();
  } else {
    await context.rebuild();
    await context.dispose();
  }
}
